name: Pull request workflow
on: 
  pull_request:
    types: [opened]

jobs:
  pull-request-create-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request creation
        run: echo "A pull request was created"